### ISSUE TITLE
Workaround for two factor auth

### ISSUE THREAD

**Issue by jma7889** [p-easterbrooks/blitz#5]
Currently the release only support https based clone, but not ssh based. For two factor auth enabled account, the tool does not work. 

A fix is needed, change line 15 of the script to
`GIT_REGEX='((https?|ftp|file)://[-A-Za-z0-9\+&@#/%?=~_|!:,.;]*[-A-Za-z0-9\+&@#/%=~_|])|((git@github.com:[^[:space:]]*).*)'`

**Comment by peaster** [comment]
resolved with #6
